### PR TITLE
Move to webpack-dev-server

### PR DESCRIPTION
**Pull request by dan-compton**
This PR replaces the invocation of (deprecated) webpack-serve with that of webpack-dev-server in internal/web_bundle/rule.bzl.   An additional file attr, `dev_server_options`, is added to _web_bundle which allows the consumer to override the default webpack-dev-server options defined in https://github.com/zenclabs/bazel-javascript/commit/8997a339d08480a5abd65508cfbe8f2eddfa9816

### CODE REVIEW

**Comment by dan-compton** [comment]
@fwouts :+1: 

Also, a couple questions for you: 

1. Have you looked at the new `rollup_bundle` in the bazelbuild/rules_nodejs?  Do you think that's an acceptable replacement for a custom webpack rule (I'm not a front-end engineer).    

2. It looks as though the web_bundle rule was written the way it was (in-part) to solve issues with webpack + bazel that. Is this correct and do those issues preclude one from simply allowing a complete webpack configuration to be provided via file attr rather than via code generation?

**Comment by fwouts** [comment]
Hi Dan,

1. I haven't looked into it in detail. My understanding is that Rollup is great for bundling ES code, but unlike webpack it doesn't have first-class support for non-ES assets such as CSS, images, etc (and webpack plugins give you a lot of flexibility). But I could be completely wrong. I simply picked webpack because that's what I was most familiar with :-)

2. The main reason for allowing a webpack config file to be passed through is that a few things need to be customised, such as the `node_modules` location needs to be provided by Bazel. There are probably better ways to do this—what do you have in mind?

**Comment by dan-compton** [comment]
1 -- Thanks for the explanation!      
2 -- I had nothing specific in mind.  I was trying to wrap my head around the trade-offs made by the dropbox implementation here: https://github.com/dropbox/rules_node/blob/master/node/defs.bzl#L786-L904

**Comment by fwouts** [comment]
Sorry, I forgot to merge this. Fixing it up and merging soon.

**Pull request merged**
